<?php
/**
 * Created by PhpStorm.
 * User: Ry Sokkheng
 * Date: 18/01/2021
 * Time: 10:22 PM
 */

namespace App\Repositories;


use App\Contracts\Repositories\UserRepositoryInterface;
use App\Models\User;
use Prettus\Repository\Criteria\RequestCriteria;

class UserRepositoryEloquent extends BaseRepository implements UserRepositoryInterface
{

    public function model()
    {
        // TODO: Implement model() method.
        return User::class;
    }

    public function boot()
    {
      $this->popCriteria(app(RequestCriteria::class));
       // TODO: Change the autogenerated stub
    }
}
